theme = "showfolio"
languageCode = "en-us"
baseurl = "https://example.com"
title = "Hyuan Farrapo"


[params]
  name = "Showfolio Theme"
  description = "Modern portfolio theme for your Hugo site."
  author = "John Doe"
  authorEmail = "hyuanpeixoto@gmail.com"
  authorImage = "/photo.jfif"
  autoDarkMode = true

  copyright = "Copyright © 2021 - John Doe · All rights reserved"
  favicon = "favicon.ico"

[params.homepage]
  title = "Hey 👋 I'm Hyuan Farrapo"
  tagline = "Game and Web Developer"
  description = "Always developing challenging and immersive experiences."
  contact = "https://www.linkedin.com/in/hyuan-peixoto/"

# [params.homepage.codepen]
#   username = "apvarun"
#   pens = ["MQaRKL", "RxodrP", "BmXGdm", "wdVypQ"]

[params.homepage.resume]
  skills = ["Unity", "Angular", "C#", "Java", "TS/JS", "Css/Sass/Less", "Scrum", ]

[[params.homepage.resume.work]]
  name = "LE@D/DELL"
  role = "Unity Developer"
  duration = "Nov 2020 - Current"

[[params.homepage.resume.work]]
  name = "LE@D/DELL"
  role = "Web Developer"
  duration = "Jun 2019 - Oct 2020"

[[params.homepage.resume.work]]
  name = "LRX-UFC"
  role = "Web Developer"
  duration = "Sep 2018 - May 2019"


# [[params.homepage.resume.courses]]

#   name = "Design Principles"
#   provider = "UX Academy"
#   duration = "Nov 2019 - Jan 2020"

[params.homepage.social]
  linkedin = "https://www.linkedin.com/in/hyuan-peixoto/"
  github = "https://github.com/Hyuan02"

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
